services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    userns_mode: "keep-id"
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - .:/var/www/html:z
    depends_on:
      - db
    networks:
      - sue-net

  db:
    image: docker.io/library/mariadb:latest # MariaDB 11 por compatibilidad con equipos antiguos
    restart: unless-stopped
    environment: # Añade los datos en el archivo `.env`
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - sue-db:/var/lib/mysql
    networks:
      - sue-net

  vite:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    entrypoint: []
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - .:/var/www/html:z
    ports:
      - "5173:5173"
    depends_on:
      - app
    networks:
      - sue-net

networks:
  sue-net:

volumes:
  sue-db: